### PR TITLE
Support for redirect using family/clan/protein name

### PR DESCRIPTION
**Pull request by matthiasblum**
Fetch primary accession in the following endpoints:
- `clan/<name>`
- `family/<name>`
- `protein/<name>`

The InterPRO REST API is used for the first two endpoints, and the UniProt REST API is used for the last one.

Also fix a small duplicated case in a switch block (8cb33ff7a24e92e71a49ef6a7b701f03db9932b1).

### CODE REVIEW

**Comment by gustavo-salazar** [comment]
@matthiasblum  please check 9c7fdd7 
* Dealing with promises because parcel was inconsistently bundling the async
* Using InterPro API for proteins and removing the UniProt one

**Comment by gustavo-salazar** [comment]
BTW, the search by entry doesn't always work, because the API only search on the fields `accession` and `name`, so if the pfam ID is not in the name, it wont find it, e.g. `7tm_1`

**Comment by matthiasblum** [comment]
> @matthiasblum please check [9c7fdd7](https://github.com/ProteinsWebTeam/pfam-redirect/commit/9c7fdd76474f1b114d95f98b74db962cc7225887)
> 
>     * Dealing with promises because parcel was inconsistently bundling the async
> 
>     * Using InterPro API for proteins and removing the UniProt one

Looks good to me :+1: 

> BTW, the search by entry doesn't always work, because the API only search on the fields `accession` and `name`, so if the pfam ID is not in the name, it wont find it, e.g. `7tm_1`

Then we could use EBI Search for entries, e.g. `query=(source_database:"pfam") AND (short_name:"7tm_1")` to search `7tm_1`.

```shell
$ curl -XGET -G 'https://www.ebi.ac.uk/ebisearch/ws/rest/interpro7' \
    --data-urlencode 'query=(source_database:"pfam") AND (short_name:"7tm_1")' \
    --data-urlencode 'format=json' 2> /dev/null \
    | python3 -m json.tool
{
    "hitCount": 1,
    "entries": [
        {
            "id": "PF00001",
            "source": "interpro7_family"
        }
    ],
    "facets": []
}
```

**Comment by gustavo-salazar** [comment]
OK changes done checking ebisearch for entries. I'm gonna approve, merge and deploy

**Pull request merged**
